name: Build and Release

on:
  push:
    tags:
      - "v*" 
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22" 

      - name: Install Fyne CLI
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Build the application
        env:
          GOOS: ${{ matrix.os == 'windows-latest' && 'windows' || 'darwin' }}
          GOARCH: ${{ matrix.os == 'windows-latest' && 'amd64' || 'arm64' }}
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            fyne package -os windows -name "HotelParse.exe"
          else
            fyne package -os darwin -name "HotelParse.app"
          fi

      - name: Create DMG (for macOS only)
        if: matrix.os == 'macos-latest'
        run: |
          mkdir dmg-folder
          mv HotelParse.app dmg-folder/
          hdiutil create HotelParse-macOS.dmg -srcfolder dmg-folder -ov -format UDZO
        shell: bash

      - name: Archive Windows executable
        if: matrix.os == 'windows-latest'
        run: |
          zip HotelParse-Windows.zip HotelParse.exe
        shell: bash

      - name: Upload release asset (macOS)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v2
        with:
          name: HotelParse-macOS
          path: HotelParse-macOS.dmg

      - name: Upload release asset (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: HotelParse-Windows
          path: HotelParse-Windows.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: HotelParse-Windows
          path: ./release

      - name: Download artifacts (macOS)
        uses: actions/download-artifact@v2
        with:
          name: HotelParse-macOS
          path: ./release

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./release/HotelParse-Windows.zip
            ./release/HotelParse-macOS.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
